development:
  adapter: postgresql
  encoding: unicode
  database: meyvn-test_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: meyvn-test_test
  pool: 5
  username: postgres
  password:
